# Generated by Django 4.2.6 on 2023-12-11 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_alter_order_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="project.order"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
